In [1]:
import numpy as np

# Sample dataset (2 features)
X = np.array([[2, 3],
    [3, 5],
    [4, 2],
    [5, 6],
    [6, 5]])

# Step 1: Mean Center the Data
X_centered = X - np.mean(X, axis=0)
X_centered

array([[-2. , -1.2],
       [-1. ,  0.8],
       [ 0. , -2.2],
       [ 1. ,  1.8],
       [ 2. ,  0.8]])

In [2]:
# Step 2: Compute Covariance Matrix
cov_matrix = np.cov(X_centered, rowvar=False)
print("Covariance Matrix:\n", cov_matrix)

Covariance Matrix:
 [[2.5  1.25]
 [1.25 2.7 ]]


In [3]:
# Step 3: Compute Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:\n", eigenvalues)

Eigenvalues:
 [1.34600638 3.85399362]


In [4]:
# Step 4: Sort eigenvalues in descending order
idx = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[idx]

eigenvectors = eigenvectors[:, idx]
print("Eigenvectors (Principal Components):\n", eigenvectors)

Eigenvectors (Principal Components):
 [[-0.6783269  -0.73476024]
 [-0.73476024  0.6783269 ]]


In [5]:
# Step 5: Explained Variance Ratio
explained_variance_ratio = eigenvalues / np.sum(eigenvalues)
print("Explained Variance Ratio:\n", explained_variance_ratio)

Explained Variance Ratio:
 [0.74115262 0.25884738]
